title: Rachel's (Arrowarchive's) Website and Digital Art Portfolio
name: Rachel
description: The hand-coded website and digital art portfolio for Rachel (Arrowarchive)
timezone: America/New_York

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
