title: Rachel's (Arrowarchive's) Official Portfolio Website
  <link rel='icon' href='favicon.ico' type='image/x-icon'/ >
name: Rachel
description: My digital art portfolio containing pieces from 2019 onwards with no signs of stopping
timezone: America/New_York

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
